"""Get the training set ready, then print the exact command to launch.

The point of this script is that the training run can be started at any time
without first working out what state the data is in. The AerialPerson download
(Zenodo 7740081, ~3.7 GB) is slow on this network and may or may not have
finished; this checks, converts it if it has, and writes a dataset yaml naming
only the sources that actually exist on disk. Ultralytics fails hard on a yaml
that lists a missing path, so generating it from reality rather than hope is
what makes "start it whenever" safe.

    python scripts/prepare_training.py            # check, convert, write yaml
    python scripts/prepare_training.py --imgsz 960 --batch 8

It never starts training itself -- it prints the command. Launching a multi-hour
GPU job is the user's call, not a side effect of a status check.
"""
import argparse
import subprocess
import sys
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DATASETS = REPO / "datasets"
YAML_PATH = REPO / "data" / "battlesight_fpv.yaml"

# (label, path relative to DATASETS, split, note)
SOURCES = [
    ("VisDrone train", "VisDrone/images/train", "train", "6471, aerial, 4 classes"),
    ("VisDrone test-dev", "VisDrone/images/test", "train",
     "1610 labelled, unused by train and val before this"),
    ("WiderPerson train", "WiderPerson/images/train", "train", "8000, ground personnel"),
    ("AerialPerson train", "AerialPerson/images/train", "train",
     "UAV personnel over natural terrain -- the missing domain"),
    ("VisDrone val", "VisDrone/images/val", "val", "548"),
    ("WiderPerson val", "WiderPerson/images/val", "val", "1000"),
    # AerialPerson's val split is DELIBERATELY NOT in this list. Its labels are
    # people only, so every correctly-detected car in it would score as a false
    # positive and drag vehicle precision down for no real reason. Pseudo-
    # labelling it instead would be worse: the pseudo-labels come from
    # drone_best.pt, which is the baseline the rubric compares against, so the
    # metric would partly reward agreeing with the model under test.
    #
    # Leaving it out has a second benefit: the val set stays identical to
    # battlesight_multi.yaml's, so eval_rubric.py numbers remain directly
    # comparable to every figure recorded in README's history.
    #
    # The 523 images stay on disk with clean ground truth as a held-out
    # on-domain set -- evaluate personnel on it explicitly when wanted:
    #   yolo val model=... data=... classes=0
]

YAML_HEADER = """\
# BattleSight AR -- generated by scripts/prepare_training.py. Do not hand-edit;
# rerun that script instead, so the file always names paths that exist.
#
# Same 4-class taxonomy as battlesight.yaml / battlesight_multi.yaml.
# battlesight_multi.yaml is deliberately left untouched so the historical
# numbers in README's "Detection accuracy work" stay reproducible against it.
#
# VisDrone's test-dev split is TRAINING data here: all 1,610 of its images
# carry ground-truth labels and were used by neither train nor val, so this is
# a free ~25% increase in VisDrone training data at no cost to any held-out
# set. AerialPerson (Zenodo 7740081, CC-BY-4.0) is the only source containing a
# person seen small from altitude against natural terrain, which is the case
# the deployed model fails hardest on.
#
# AerialPerson contributes to TRAIN ONLY. Its val split is held out of the
# metric on purpose -- it labels people but not the many cars in its aerial
# imagery, so scoring vehicles against it would be meaningless, and pseudo-
# labelling it would partly measure agreement with the baseline model that
# generated those labels. The val set here is therefore identical to
# battlesight_multi.yaml's, which keeps eval_rubric.py numbers directly
# comparable to the figures recorded in README's history.
#
# AerialPerson's TRAIN labels DO carry vehicle pseudo-labels (see
# scripts/pseudo_label_vehicles.py and README 16g) -- without them its ~258,000
# unlabelled cars would train the model to treat aerial vehicles as background.
"""


def parse_args():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--imgsz", type=int, default=1280,
                   help="Training resolution for the printed command. 1280 matches "
                        "config.IMGSZ, i.e. what the model is actually served at; "
                        "the deployed checkpoints were trained at 640, which is a "
                        "real train/serve mismatch on tiny targets.")
    p.add_argument("--batch", type=int, default=4,
                   help="Batch size for the printed command. Verify against the "
                        "VRAM probe before trusting a larger value on this 8 GB GPU.")
    p.add_argument("--epochs", type=int, default=8,
                   help="8, not 40. At imgsz 1280 / batch 4 this machine runs "
                        "~51 min/epoch over the full 18,694-image train set, so 8 "
                        "epochs is about 7 h -- the stated budget. This is a "
                        "fine-tune from a trained checkpoint, not a run from scratch.")
    p.add_argument("--name", default="battlesight_fpv")
    p.add_argument("--skip-convert", action="store_true",
                   help="Do not run convert_aerialperson.py even if the archive looks complete")
    return p.parse_args()


def archive_complete(path: Path) -> bool:
    """True if the zip is fully downloaded and readable.

    A partial file from an interrupted transfer still exists and still has a
    plausible size, so testing existence is not enough -- read the central
    directory, which lives at the END of a zip and is therefore exactly what a
    truncated download lacks.
    """
    if not path.exists():
        return False
    try:
        with zipfile.ZipFile(path) as z:
            return z.testzip() is None or True
    except zipfile.BadZipFile:
        return False


def main():
    args = parse_args()

    raw = DATASETS / "AerialPerson_raw"
    converted = DATASETS / "AerialPerson" / "images" / "train"
    images_zip = raw / "Images.zip"

    print("=" * 72)
    print("AerialPerson (Zenodo 7740081)")
    if converted.exists() and any(converted.iterdir()):
        print("  already converted -> {}".format(converted))
    elif not images_zip.exists():
        print("  Images.zip not downloaded yet -- training will proceed without it.")
    elif not archive_complete(images_zip):
        size_gb = images_zip.stat().st_size / 1e9
        print("  Images.zip is still downloading ({:.2f} GB of ~3.72 GB) --"
              .format(size_gb))
        print("  training will proceed without it. Rerun this script once it lands.")
    elif args.skip_convert:
        print("  archive complete, but --skip-convert was passed")
    else:
        print("  archive complete; converting...")
        result = subprocess.run(
            [sys.executable, str(REPO / "scripts" / "convert_aerialperson.py")],
            cwd=str(REPO))
        if result.returncode != 0:
            print("  conversion FAILED; continuing without this dataset")

    # AerialPerson annotates PEOPLE ONLY, over top-down aerial imagery full of
    # parked cars -- the same viewpoint VisDrone teaches vehicles from. Mixing
    # it in raw presents ~258,000 unlabelled vehicles as confirmed negatives.
    # Refuse to do that silently; see scripts/pseudo_label_vehicles.py.
    if (DATASETS / "AerialPerson" / "images" / "train").is_dir():
        if not (DATASETS / "AerialPerson" / "labels" / "train.orig").is_dir():
            print("=" * 72)
            print("!! WARNING: AerialPerson vehicle pseudo-labels are MISSING.")
            print("   That dataset labels people only, but its aerial imagery is")
            print("   full of unlabelled cars (~97/image measured). Training on it")
            print("   as-is teaches the model that aerial vehicles are background")
            print("   and will damage light_vehicle/heavy_vehicle. Run first:")
            print("       python scripts/pseudo_label_vehicles.py")
            print("   (or pass --skip-convert and drop AerialPerson from the yaml)")

    print("=" * 72)
    print("Dataset sources")
    present = {"train": [], "val": []}
    for label, rel, split, note in SOURCES:
        path = DATASETS / rel
        count = len(list(path.glob("*"))) if path.is_dir() else 0
        if count:
            present[split].append(rel)
            print("  [x] {:<20} {:>6} images  {}".format(label, count, note))
        else:
            print("  [ ] {:<20} {:>6}          MISSING -- omitted from the yaml"
                  .format(label, 0))

    if not present["train"] or not present["val"]:
        raise SystemExit("\nNo usable train or val sources; nothing to write.")

    lines = [YAML_HEADER, "path: {}".format(DATASETS.as_posix()), "", "train:"]
    lines += ["  - {}".format(p) for p in present["train"]]
    lines += ["", "val:"]
    lines += ["  - {}".format(p) for p in present["val"]]
    lines += ["", "names:", "  0: personnel", "  1: two_wheeler",
              "  2: light_vehicle", "  3: heavy_vehicle", ""]
    YAML_PATH.write_text("\n".join(lines), encoding="utf-8")
    print("\nwrote {}".format(YAML_PATH))

    print("=" * 72)
    print("Start training with:\n")
    print("  python scripts/train.py \\\n"
          "      --model weights/best.pt \\\n"
          "      --data data/battlesight_fpv.yaml \\\n"
          "      --aug-profile fpv \\\n"
          "      --imgsz {} --batch {} --epochs {} \\\n"
          "      --lr0 0.002 --flipud 0 \\\n"
          "      --name {}".format(args.imgsz, args.batch, args.epochs, args.name))
    print("\nThen, before promoting anything:\n")
    print("  python scripts/eval_rubric.py runs/detect/{}/weights/best.pt \\\n"
          "      --baseline weights/best.pt --data data/battlesight_fpv.yaml "
          "--imgsz {}".format(args.name, args.imgsz))


if __name__ == "__main__":
    main()
